In [4]:
import numpy as np

In [5]:
# versão
print(np.__version__)

1.21.6


In [6]:
# criar matriz 

array = np.array([10,20,30,40,50])

In [7]:
type( array )

numpy.ndarray

In [8]:
# duas dimensões 

duas_array = np.array([[1,19,29,35,77],
                        [23,12,65,43,23]])
print(duas_array)

[[ 1 19 29 35 77]
 [23 12 65 43 23]]


In [11]:
# Três dimensões 

tres_array = np.array([
                       [15,65,46,78,7,4,1],
                       [1,23,43,2,5,6,3],
                       [34,65,44,6,8,9,10]
                       ]);
print(tres_array)

[[15 65 46 78  7  4  1]
 [ 1 23 43  2  5  6  3]
 [34 65 44  6  8  9 10]]


In [13]:
np_estresse = np.arange(1000)
np_estresse2 = np.arange(20000000)
np_estresse3 = np.arange(50000000)

len(np_estresse), len(np_estresse2)

(1000, 20000000)

In [14]:
# 1° teste
%time for loop in np_estresse : pass

CPU times: user 0 ns, sys: 83 µs, total: 83 µs
Wall time: 86.5 µs


In [15]:
%time for loop in np_estresse2: pass

CPU times: user 1.36 s, sys: 11.5 ms, total: 1.37 s
Wall time: 1.38 s


In [16]:
%time for loop in np_estresse3 : pass

CPU times: user 3.43 s, sys: 0 ns, total: 3.43 s
Wall time: 3.43 s


In [17]:
# Acessar os arrays 
array
# 1° posição
array[0]

10

In [18]:
#ultima posição
array[-1]

50

In [19]:
# operações pega a posição 1 + a posição -2
print(array[1], array[-2])
array[1] + array[-2]

20 40


60

In [20]:
# Range
array[2:]

array([30, 40, 50])

In [21]:
#operação lógica
array[0] == array[1]

False

In [22]:
array[0] <= array[1]

True

In [23]:
array[3] != array[2]

True

In [24]:
for loop in array:
  print(loop)

10
20
30
40
50


In [25]:
array.shape

(5,)

In [26]:
# loop 
for loop in duas_array:
  print(loop)

[ 1 19 29 35 77]
[23 12 65 43 23]


In [27]:
duas_array.shape

(2, 5)

In [31]:
# percorrendo todos os resultados

for loop in duas_array:
  for interno in loop:
   print(interno)

1
19
29
35
77
23
12
65
43
23


In [32]:
import pandas  as pd

In [35]:
pd.DataFrame(duas_array)

0   1   2   3   4
0   1  19  29  35  77
1  23  12  65  43  23